FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime

LABEL description="Latest PyTorch and Ignite"

RUN apt-get update && apt-get install -y --no-install-recommends git wget && \
     rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/pytorch/ignite.git /tmp/ignite && \
    cp -R /tmp/ignite/examples /workspace/pytorch-ignite-examples

RUN pip install tensorboard tqdm pytorch-ignite

ENTRYPOINT ["/bin/bash"]