FROM pytorchignite/hvd-base

LABEL description="Latest PyTorch, Ignite, Horovod + libraries for computer vision"


# Install OpenCV
RUN apt-get update && ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && \
    apt-get install -y tzdata && \
    dpkg-reconfigure --frontend noninteractive tzdata && \
    apt-get -y install --no-install-recommends libglib2.0 libsm6 libxext6 libxrender-dev